apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: external-secrets
      namespace: openshift-gitops
    path: patches/patch-app-external-secrets.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: kyverno
      namespace: openshift-gitops
    path: patches/patch-app-kyverno.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: cert-manager
      namespace: openshift-gitops
    path: patches/patch-app-cert-manager.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: cloudnative-pg
      namespace: openshift-gitops
    path: patches/patch-app-cloudnative-pg.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: nmstate
      namespace: openshift-gitops
    path: patches/patch-app-nmstate.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: node-feature-discovery
      namespace: openshift-gitops
    path: patches/patch-app-node-feature-discovery.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: step-issuer-controller
      namespace: openshift-gitops
    path: patches/patch-app-step-issuer-controller.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: ca-trust
      namespace: openshift-gitops
    path: patches/patch-app-ca-trust.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: step-cluster-issuer
      namespace: openshift-gitops
    path: patches/patch-app-step-cluster-issuer.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: ingress-cert
      namespace: openshift-gitops
    path: patches/patch-app-ingress-cert.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: api-cert
      namespace: openshift-gitops
    path: patches/patch-app-api-cert.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: lvm-storage
      namespace: openshift-gitops
    path: patches/patch-app-lvm-storage.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: seaweedfs
      namespace: openshift-gitops
    path: patches/patch-app-seaweedfs.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: keycloak
      namespace: openshift-gitops
    path: patches/patch-app-keycloak.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: quay
      namespace: openshift-gitops
    path: patches/patch-app-quay.yaml
