apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-nmstate

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - nmstate.yaml

commonLabels:
  component: nmstate
