- ansible.builtin.include_tasks: os-packages.yaml
- ansible.builtin.include_tasks: user.yaml
- ansible.builtin.include_tasks: access.yaml
- ansible.builtin.include_tasks: services.yaml
- ansible.builtin.include_tasks: firewall.yaml
