apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quay-seaweedfs
spec:
  secretName: quay-seaweedfs-certificate
  duration: 1440h
  renewBefore: 72h
  issuerRef:
    group: certmanager.step.sm
    kind: StepClusterIssuer
    name: step-cluster-issuer
  usages:
    - server auth
  commonName: admin.seaweedfs-quay.apps.polaris.lab.cross.solutions
  dnsNames:
    - admin.seaweedfs-quay.apps.polaris.lab.cross.solutions
