apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base

components:
  - ../../components/annotation-resource-tracking
  - ../../components/application-controller-cluster-admin
  - ../../components/edge-termination
  - ../../components/enable-notifications
  - ../../components/enable-status-badge
  - ../../components/gitops-admins
  - ../../components/health-check-olm
  - ../../components/health-check-openshift-builds
  - ../../components/enable-progressive-sync
  - ../../components/kustomize-build-enable-helm
