[project]
name = "openshift-virt-ee"
version = "0.1.0"
description = "Ansible EE for working with OpenShift Virtualization"
readme = "README.md"
requires-python = ">=3.13.8"
dependencies = []

[dependency-groups]
dev = [
    "ansible-builder>=3.1",
    "ansible-sign>=0.1.2",
]
ee = []
