apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-nfd

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - nodefeaturediscovery.yaml

commonLabels:
  component: node-feature-discovery
