apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../components/advanced-cluster-management/operator/overlays/release-2.15
  - ../../../../../components/advanced-cluster-management/instance/overlays/default
