apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - use-nonroot-v2-scc.yaml
  - allow-cnpg-sa-nonroot-v2.yaml

helmCharts:
  - name: cloudnative-pg
    repo: 'https://cloudnative-pg.github.io/charts'
    releaseName: cnpg
    version: 0.27.0
    valuesFile: helm-values/cnpg.yaml
    namespace: cnpg-system
    includeCRDs: true
