kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonAnnotations:
  argocd.argoproj.io/sync-wave: "15"

resources:
  - cluster-ingress-wildcard-certificate.yaml
  - patch-cluster-ingress-wildcard-cert-job.yaml
