kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-ingress

commonAnnotations:
  argocd.argoproj.io/sync-wave: "15"

resources:
  - openshift-wildcard-certificate.yaml
  - mirrored-secret-openshift-wildcard-certificate.yaml
  - patch-cluster-wildcard-cert-job.yaml
