apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-ingress-wildcard
  namespace: pki
spec:
  secretName: lab-ingress-wildcard-certificate
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "openshift-ingress"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "openshift-ingress"
  duration: 1440h
  renewBefore: 72h
  issuerRef:
    group: certmanager.step.sm
    kind: StepIssuer
    name: step-issuer
  commonName: '*.apps.core.lab.cross.solutions'
  dnsNames:
    - '*.apps.core.lab.cross.solutions'
