apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-cluster-ingress-wildcard-cert
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - ingresscontrollers
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-cluster-ingress-wildcard-cert
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-cluster-ingress-wildcard-cert
subjects:
  - kind: ServiceAccount
    name: patch-cluster-ingress-wildcard-cert
    namespace: openshift-ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-cluster-ingress-wildcard-cert
  namespace: openshift-ingress
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-cluster-ingress-wildcard-cert
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift/origin-cli:latest
          env:
            - name: NAMESPACE
              value: openshift-ingress
            - name: SECRET
              value: cluster-ingress-wildcard-certificate
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash

              until oc -n "$NAMESPACE" get secret "$SECRET" >/dev/null 2>&1; do
                echo "Waiting for $NAMESPACE/$SECRET to exist..."
                sleep 5
              done

              until oc -n "$NAMESPACE" get secret "$SECRET" -o jsonpath='{.data.tls\.crt}' | grep -q . && \
                    oc -n "$NAMESPACE" get secret "$SECRET" -o jsonpath='{.data.tls\.key}' | grep -q .; do
                echo "Waiting for tls.crt/tls.key to be present in $NAMESPACE/$SECRET..."
                sleep 5
              done

              oc patch ingresscontroller.operator default -n openshift-ingress-operator --type=merge --patch='{"spec": { "defaultCertificate": { "name": "'"$SECRET"'" }}}'
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              if oc get secret  -n openshift-ingress; then
                oc patch ingresscontroller default -n openshift-ingress-operator --type=merge --patch='{"spec": { "defaultCertificate": { "name": "lab-ingress-wildcard-certificate" }}}'
              else
                echo "Could not execute sync as secret 'lab-ingress-wildcard-certificate' in namespace 'openshift-ingress' does not exist, check status of CertificationRequest"
                exit 1
              fi
          name: patch-cluster-ingress-wildcard-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: patch-cluster-ingress-wildcard-cert
      serviceAccountName: patch-cluster-ingress-wildcard-cert
