apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: lab-ca-bundle
    namespace: openshift-config
    files:
      - ca-bundle.crt

resources:
  - proxy.yaml
  - patch-cluster-root-ca.yaml
