apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-keycloak-admin-creds.yaml
  - secret-keycloak-db-creds.yaml
  - secret-keycloak-tls.yaml
  - postgres.yaml
  - ../../../../components/10-platform/keycloak/operator/overlays/stable-v26.4
  - ../../../../components/10-platform/keycloak/instance/overlays/default

patchesStrategicMerge:
  - patches/patch-keycloak.yaml