apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

resources:
  - ../../base

components:
  - ../../components/enable-multicluster-observability
  - ../../components/enable-siteconfig
