---
step_ca_image_uri: ghcr.io/wtcross/step-ca:latest

step_uid: 1001
step_gid: 1001
step_user: step
step_group: step
step_user_home: /home/{{ step_user }}

_step_os_packages:
  - acl
  - firewalld
  - python3-firewall
  - pcsc-lite
  - opensc
  - p11-kit
  - p11-kit-server
  - gnutls-utils

_step_data_mount_target: /home/step/.step
