apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cudn-storage.yaml
  - mc-configure-iscsi-initiatorname.yaml
  - mc-enable-iscsi.yaml
  - namespace.yaml

commonLabels:
  component: storage