apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ingress-wildcard
  namespace: openshift-ingress
spec:
  secretName: cluster-ingress-wildcard-certificate
  duration: 1440h
  renewBefore: 72h
  issuerRef:
    group: certmanager.step.sm
    kind: StepClusterIssuer
    name: step-issuer
  commonName: '*.apps.core.lab.cross.solutions'
  dnsNames:
    - '*.apps.core.lab.cross.solutions'
