apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/external-secrets/operator/overlays/stable-v1
  - ns-external-secrets.yaml
  - clustersecretstore.yaml
