apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base

components:
  - ../../components/annotation-resource-tracking
  - ../../components/application-controller-cluster-admin
  - ../../components/edge-termination
  - ../../components/enable-notifications
  - ../../components/enable-status-badge
  - ../../components/gitops-admins
  - ../../components/health-check-olm
  - ../../components/health-check-openshift-builds
  - ../../components/kustomize-build-enable-helm
  - ../../components/kustomize-build-acm-2.15-policy-generator

patches:
  - target:
      kind: ArgoCD
    path: patch-kustomize-build-options.yaml
