apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/05-infra/infra-secrets
  # - ../../../components/05-infra/advanced-cluster-management/operator/overlays/release-2.15
  # - ../../../components/05-infra/advanced-cluster-management/instance/base
  - ../../../components/05-infra/nmstate
  - ../../../components/05-infra/node-feature-discovery

patches:
  - target:
      group: external-secrets.io
      version: v1
      kind: ClusterSecretStore
      name: infra-gcpsm-store
      namespace: external-secrets
    path: patches/patch-infra-clustersecretstore.yaml
