apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
  argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true

resources:
  - ../../base

generators:
  - ../../generators/overlays/chart-version-3.6.1
