apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - use-anyuid-seccomp-scc.yaml
  - allow-default-sa-anyuid-seccomp.yaml

helmCharts:
  - name: harbor
    repo: 'https://helm.goharbor.io'
    releaseName: harbor
    version: 1.18.0
    valuesFile: helm-values/harbor.yaml
    namespace: harbor
    includeCRDs: true