apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecretsConfig
metadata:
  annotations:
    operator.openshift.io/external-secrets-processed: 'true'
    argocd.argoproj.io/sync-wave: "1"
  name: cluster
  labels:
    app: external-secrets-operator
spec:
  appConfig:
    logLevel: 1
  controllerConfig: {}
  plugins: {}
