apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: k8s.keycloak.org
      version: v2alpha1
      kind: Keycloak
      name: keycloak
      namespace: keycloak
    path: patches/patch-keycloak.yaml
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: keycloak
      namespace: keycloak
    path: patches/patch-keycloak-certificate.yaml
