apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-external-vms.yaml
  - secret-external-vm-cloud-init-userdata.yaml
  - nncp-lab-external.yaml
  - cudn-lab-external.yaml
  - virtual-machines
