apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-wave: "3"

resources:
  - secret-lab-ca-root.yaml
  - secret-lab-ca-bundle.yaml
  - trust-bundle-lab-ca.yaml
  - cluster-proxy.yaml
