apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns-trust-manager.yaml

helmCharts:
  - name: trust-manager
    repo: https://charts.jetstack.io
    releaseName: trust-manager
    version: v0.20.3
    valuesFile: helm-values/trust-manager.yaml
    namespace: trust-manager
    includeCRDs: true
