apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/05-infra/infra-secrets
  - ../../../components/05-infra/nmstate
  - ../../../components/05-infra/node-feature-discovery
  - ../../../components/05-infra/reflector
  - nncp-br-storage.yaml
  - ../../../components/05-infra/storage
  - csi-driver-fast-iscsi
  - csi-driver-fast-nfs
  - csi-driver-tank-nfs

patches:
  - target:
      group: external-secrets.io
      version: v1
      kind: ClusterSecretStore
      name: infra-gcpsm-store
      namespace: external-secrets
    path: patches/patch-infra-clustersecretstore.yaml
