apiVersion: batch/v1
kind: Job
metadata:
  generateName: rhbk-configure-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ansible
          image: ghcr.io/wtcross/keycloak-ee:latest
          command: ["/bin/bash","-lc"]
          args:
            - |
              set -euo pipefail
              ansible-playbook -i /inventory/inventory.ini /project/rhbk-configure.yml
          env:
            - name: KEYCLOAK_URL
              value: keycloak-service.keycloak.svc.cluster.local
            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-creds
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-creds
                  key: password
          volumeMounts:
            - name: cm-inventory
              mountPath: /inventory
            - name: cm-playbook
              mountPath: /project
      volumes:
        - name: cm-inventory
          configMap:
            name: rhbk-configure-inventory
        - name: cm-playbook
          configMap:
            name: rhbk-configure-playbook
