apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-wave: "15"

namespace: keycloak

resources:
  - cm-inventory.yaml
  - cm-playbook.yaml
  - job-playbook-run.yaml
