apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/10-platform/scc
  - ../../../components/10-platform/cloudnative-pg/operator/overlays/stable-v1
  # - keycloak
  # - harbor
