apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-operator/operator/overlays/stable-v1.18
  - trust-manager
  - ns-pki.yaml
  - lab-ca-trust
  - step-issuer
