apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-wave: "1"

resources:
  - cert-manager-operator/operator/overlays/stable-v1.18
  - trust-manager
  - ns-pki.yaml
  - lab-ca-trust
  - step-issuer
  - cluster-wildcard-certificate
  - cluster-api-certificate
