apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - admin-cert.yaml
  - filer-cert.yaml
  - master-cert.yaml
  - volume-cert.yaml
  - worker-cert.yaml
  - client-cert.yaml
