apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-wave: "5"

resources:
  - namespace.yaml

helmCharts:
  - name: democratic-csi
    repo: 'https://democratic-csi.github.io/charts/'
    releaseName: democratic-csi-tank-nfs
    version: 0.15.0
    valuesFile: helm-values/vault.yaml
    namespace: democratic-csi
    includeCRDs: false

