apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-wave: "7"

resources:
  - es-s3-config.yaml
  - es-seaweed-admin-creds.yaml
  - admin-ingress-certificate.yaml
  - pvc-worker-data.yaml
  - pvc-worker-logs.yaml
  # - job-create-bucket.yaml

helmCharts:
  - name: seaweedfs
    repo: 'https://seaweedfs.github.io/seaweedfs/helm'
    releaseName: seaweedfs
    version: 4.0.405
    valuesFile: helm-values/seaweedfs.yaml
    namespace: quay
